<?php
declare(strict_types=1);

// PassantenfrequenzenZuerich SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

PassantenfrequenzenZuerichUtility::setRegistrar(function (PassantenfrequenzenZuerichUtility $u): void {
    $u->clean = [PassantenfrequenzenZuerichClean::class, 'call'];
    $u->done = [PassantenfrequenzenZuerichDone::class, 'call'];
    $u->make_error = [PassantenfrequenzenZuerichMakeError::class, 'call'];
    $u->feature_add = [PassantenfrequenzenZuerichFeatureAdd::class, 'call'];
    $u->feature_hook = [PassantenfrequenzenZuerichFeatureHook::class, 'call'];
    $u->feature_init = [PassantenfrequenzenZuerichFeatureInit::class, 'call'];
    $u->fetcher = [PassantenfrequenzenZuerichFetcher::class, 'call'];
    $u->make_fetch_def = [PassantenfrequenzenZuerichMakeFetchDef::class, 'call'];
    $u->make_context = [PassantenfrequenzenZuerichMakeContext::class, 'call'];
    $u->make_options = [PassantenfrequenzenZuerichMakeOptions::class, 'call'];
    $u->make_request = [PassantenfrequenzenZuerichMakeRequest::class, 'call'];
    $u->make_response = [PassantenfrequenzenZuerichMakeResponse::class, 'call'];
    $u->make_result = [PassantenfrequenzenZuerichMakeResult::class, 'call'];
    $u->make_point = [PassantenfrequenzenZuerichMakePoint::class, 'call'];
    $u->make_spec = [PassantenfrequenzenZuerichMakeSpec::class, 'call'];
    $u->make_url = [PassantenfrequenzenZuerichMakeUrl::class, 'call'];
    $u->param = [PassantenfrequenzenZuerichParam::class, 'call'];
    $u->prepare_auth = [PassantenfrequenzenZuerichPrepareAuth::class, 'call'];
    $u->prepare_body = [PassantenfrequenzenZuerichPrepareBody::class, 'call'];
    $u->prepare_headers = [PassantenfrequenzenZuerichPrepareHeaders::class, 'call'];
    $u->prepare_method = [PassantenfrequenzenZuerichPrepareMethod::class, 'call'];
    $u->prepare_params = [PassantenfrequenzenZuerichPrepareParams::class, 'call'];
    $u->prepare_path = [PassantenfrequenzenZuerichPreparePath::class, 'call'];
    $u->prepare_query = [PassantenfrequenzenZuerichPrepareQuery::class, 'call'];
    $u->graphql_body = [PassantenfrequenzenZuerichGraphql::class, 'body'];
    $u->graphql_errors = [PassantenfrequenzenZuerichGraphql::class, 'errors'];
    $u->result_basic = [PassantenfrequenzenZuerichResultBasic::class, 'call'];
    $u->result_body = [PassantenfrequenzenZuerichResultBody::class, 'call'];
    $u->result_headers = [PassantenfrequenzenZuerichResultHeaders::class, 'call'];
    $u->transform_request = [PassantenfrequenzenZuerichTransformRequest::class, 'call'];
    $u->transform_response = [PassantenfrequenzenZuerichTransformResponse::class, 'call'];
});
